[tox]
envlist = py39, py310, py311, py312, py313

[testenv]
deps=
	pytest
	coverage
commands=
	coverage run --source=electrum '--omit=electrum/gui/*,electrum/plugins/*,electrum/scripts/*,electrum/tests/*' -m py.test -v
	coverage report
extras=
	tests
